FROM openjdk:8-jdk-alpine
VOLUME /tmp
COPY ../config-server/target/config-server-1.0.jar app.jar
RUN apk add --update curl && \
    rm -rf /var/cache/apk/*
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]