version: '3'

services:

  configserver:
    build:
      context: ./
      dockerfile: dockerfile-config-server
    image: mc-sample/config-server:latest
    ports:
      - "8888:8888"
    depends_on:
      - "rabbitmq"
    networks:
      - mc-sample-network

  eureka1:
    build:
      context: ./
      dockerfile: dockerfile-eureka1
    image: mc-sample/eureka1:latest
    ports:
      - "9998:9998"
    networks:
      mc-sample-network:
        aliases:
          - eureka1

  eureka2:
    build:
      context: ./
      dockerfile: dockerfile-eureka2
    image: mc-sample/eureka2:latest
    ports:
      - "9999:9999"
    networks:
      mc-sample-network:
        aliases:
          - eureka2

  rabbitmq:
    container_name: rabbit-for-microservices-sample
    build:
      context: ./
      dockerfile: dockerfile-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mc-sample-network


networks:
  mc-sample-network:
