---
spring:
  profiles: eureka1
  application:
    name: eureka1

server:
  port: 9998

eureka:
  instance:
    hostname: eureka1
  client:
    serviceUrl:
      defaultZone: http://eureka2:9999/eureka/

---
spring:
  profiles: eureka2
  application:
    name: eureka2

server:
  port: 9999

eureka:
  instance:
    hostname: eureka2
  client:
    serviceUrl:
      defaultZone: http://eureka1:9998/eureka/