feign:
    hystrix:
        enabled: true
hystrix:
    command:
        default:
            circuitBreaker:
                requestVolumeThreshold: 3
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 5000
management:
    endpoint:
        health:
            sensitive: false
            show-details: ALWAYS
    endpoints:
        web:
            exposure:
                include: '*'

