feign:
    hystrix:
        enabled: true
hystrix:
    command:
        default:
            circuitBreaker:
                requestVolumeThreshold: 3
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 5000
