#properties file to configure this server
server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sodemir/microservices-with-spring-netflix-docker
          searchPaths : config-repository
#        native:
#          searchLocations: classpath:config-repo/


#actuators
management:
  endpoint:
    health:
      sensitive:  false
      show-details: ALWAYS

#rabbit-mq
#spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

endpoints:
  restart:
    enabled: true
